### ISSUE TITLE
Error 1049: Unknown database 'subscan'

### ISSUE THREAD

**Issue by anizeani** [itering/subscan-essentials#131]
When I run the docker container, The subscan api crashes and the log says: 
goroutine 1 [running]:
github.com/itering/subscan/internal/dao.newDb(0xc0003745c0, 0x9, 0xc0003745e8, 0x4, 0x0, 0x0, 0xc000374640, 0x7, 0xc00033bc80, 0xc00033bd40, ...)
        /subscan/internal/dao/db.go:211 +0x3d8
github.com/itering/subscan/internal/dao.New(0xc00037fa40, 0xc00031fb20)
        /subscan/internal/dao/dao.go:26 +0xee
github.com/itering/subscan/internal/service.New(0x80)
        /subscan/internal/service/service.go:24 +0x4f
main.run()
        /subscan/cmd/main.go:82 +0x34
main.setupApp.func1(0xc0003566e0, 0x0, 0x0)
        /subscan/cmd/main.go:37 +0x20
github.com/urfave/cli.HandleAction(0xb44d20, 0xc842d0, 0xc0003566e0, 0xc00033b7a0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc0000b2680, 0xc0000201e0, 0x1, 0x1, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x5dd
main.main()
        /subscan/cmd/main.go:26 +0x71
2021/06/11 09:17:51 start watch filepath: ../configs
panic: Error 1049: Unknown database 'subscan'

Any ideas how to fix this?

**Comment by kylezs** [comment]
I've got the same error, if you've got discord: kylezs#9918

**Comment by kylezs** [comment]
This should fix it: https://github.com/itering/subscan-essentials/pull/132

I did encounter an error related to not being able to login after this, due to the mysql root user only accepting `root`@`localhost`. 
I fixed it by doing:
`GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password'`

Where "password" is the password being used in the configuration, by default this is `helloload`

**Comment by freehere107** [comment]
@kylezs @anizeani https://github.com/itering/subscan-essentials/pull/132  has merged
